export const enrollBtn = (props) => ({
  background: `${props.buttonBackground} 0% 0% no-repeat padding-box`,
  boxShadow: "0px 3px 2px #2700FF29",
  borderRadius: "2rem",
  opacity: 1,
  height: "3.5rem",
  width: "14rem",
  color: `${props.buttonColor}`,
  font: "normal normal normal 1.5rem/1.75rem Lato",
  textTransform: "none",
  marginTop: "2rem",
  "@media (max-width:1260px)": {
    fontSize: "1.25rem",
    lineHeight: "1.75rem",
    height: "2.5rem",
    width: "fit-content", //`${(18.75 / 5.625) * 4}rem`,
    borderRadius: `${(2 / 5.625) * 2}rem`,
    padding: "1rem",
  },
});
